In [4]:
import numpy as np

In [7]:
### creating a 1 dimensional array
my1dArray = np.array([1,2,3])
print(my1dArray)

[1 2 3]


In [8]:
### 2 dimensional array
my2dArray = np.array([[1,2,3],[4,5,6]])
print(my2dArray)

[[1 2 3]
 [4 5 6]]


In [19]:
##creating an array specifying the datatype:
my2dArrayfloat = np.array([[1,2,3],[4,5,6]], dtype="float")
print(my2dArrayfloat)
my2dArrayfloat.dtype

[[1. 2. 3.]
 [4. 5. 6.]]


dtype('float64')

In [20]:
##creating a 2d Array in another form:
my2dArrayfloat = np.array([[1,2,3],[4,5,6]], dtype=np.float16)
print(my2dArrayfloat)
my2dArrayfloat.dtype

[[1. 2. 3.]
 [4. 5. 6.]]


dtype('float16')

In [23]:
##creating an array with multiple data type
charArray1 = np.array([(1, "a", 3),(4,5,"zzzlkz")], dtype="U4")
print(charArray1)

charArray1.dtype

[['1' 'a' '3']
 ['4' '5' 'zzzl']]


dtype('<U4')

In [28]:


##create an array
RaduArray = np.array([("Apple","Orange","Pears"),(7,9,3)], dtype="U5")



###print the array and print the dtype
print(RaduArray)

###indicate the data type of the array
RaduArray.dtype

[['Apple' 'Orang' 'Pears']
 ['7' '9' '3']]


dtype('<U5')

In [32]:
# numpy initialisation

number_rows = 2

number_collumns = 3

##creating arrays of zeros, specifying the data type:
array0s = np.zeros((number_rows, number_collumns), dtype=np.int16)
print(array0s)

[[0 0 0]
 [0 0 0]]


In [34]:
#creating arrays of one
array1s = np.ones((number_rows,number_collumns), dtype="float16")

print(array1s)

[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
###create arrays of 5
array5s = array1s * 5
print(array1s)

[[1. 1. 1.]
 [1. 1. 1.]]


In [37]:
###create arrays of 5 (without creating arrays1s)
array5s = 5 * np.ones((number_rows, number_collumns), dtype="float32")
print(array5s)

[[5. 5. 5.]
 [5. 5. 5.]]


In [40]:
array7s = np.full ((number_rows, number_collumns), 20)
print(array7s)

[[20 20 20]
 [20 20 20]]


In [44]:
##creating an array of evenly spaced values:
start = 10
end  = 26
step = 3

EvenlyStep= np.arange(start, end, step)
## **last number (from "e"nd") not included

print(EvenlyStep)


[10 13 16 19 22 25]


In [46]:
## create an array with "linspace"

number_samples = 3
evenly_sample = np.linspace(start,end,number_samples) 
## **Last number (from "end") included with "linspace" function
##linspace - always a float result

print(evenly_sample)

[10. 18. 26.]


In [53]:
##create an identity matrix:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
random01 = np.random.random((2,3))
print(random01)

[[0.21289206 0.98631548 0.71105207]
 [0.02458834 0.38941288 0.48893809]]


In [56]:
##
randomNum = np.random.randint(0, 10, (2,3))

print(randomNum)

[[7 9 2]
 [7 6 8]]


In [58]:
randomFloat = np.random.uniform(10.5,25.7, (2,3))

print(randomFloat)


[[18.4374005  22.07778696 25.37876021]
 [10.97808408 16.15339935 20.56380468]]


In [62]:
## array ininspection indexing and slicing

a = np.array([[4,6,7], [7,9,11]])

##find the dimension of the array
print("a has a dimension:" , a.ndim)
print("a has shape:" , a.shape)
print("a has size:" , a.size)
print("a has data type" , a.dtype)

a has a dimension: 2
a has shape: (2, 3)
a has size: 6
a has data type int64


In [65]:
print(a)

[[ 4  6  7]
 [ 7  9 11]]


In [68]:
###inspecting the array
a[0,0:3]

array([4, 6, 7])

In [70]:
a[a<3]

array([], dtype=int64)

In [73]:
## diagonal
b =np.array([[5, 6, 7], [1, 4, 5],[2,2,2]])
print(b)

[[5 6 7]
 [1 4 5]
 [2 2 2]]


In [74]:
np.diag(b)

array([5, 4, 2])

In [17]:
#np aray task1
import numpy as np
### generating numpy arrai
arr = np.array([0,2,4,5,3,7,8,9,5,1])

#find odd number and replace them with their negative value, but for numbers below 7
arr[(arr %2 ==1) & (arr < 7)] = -1 * arr[(arr %2 ==1) & (arr < 7)]

print(arr[arr < 7])

[ 0  2  4 -5 -3 -5 -1]


In [8]:
import numpy as np
a = np.array([[1,2,5],[7,1,3]])
b = np.array([[4,6,9],[2,5,1]])

In [9]:
### multiplication of array
mul1 =a*b
mul2 = np.multiply(a,b)
print(mul1)
print (mul2)

[[ 4 12 45]
 [14  5  3]]
[[ 4 12 45]
 [14  5  3]]


In [13]:
div = a/bdiv2 = np.divide(a, b)
print(div1)
print(div2)

SyntaxError: cannot assign to expression (2633780326.py, line 1)

In [12]:
## other operations
##exponential
ex =np.exp(a)

##square root
sqroot = np.sqrt(a)

#sin

find_si = np.sin(a)
find_co = np.cos(a)


In [14]:
print(find_si)

[[ 0.84147098  0.90929743 -0.95892427]
 [ 0.6569866   0.84147098  0.14112001]]


In [15]:
print(find_co)

[[ 0.54030231 -0.41614684  0.28366219]
 [ 0.75390225  0.54030231 -0.9899925 ]]


In [16]:
print(find_lg)

NameError: name 'find_lg' is not defined

In [17]:
b.shape

(2, 3)

In [18]:
c = np.array([[5,6], [3,5], [8,2]])
c.shape

(3, 2)

In [19]:
## dot product calculation
dotp = a.dot(c)
print(dotp)

[[51 26]
 [62 53]]


In [20]:
## statistics for this array
d=np.array([[1,2,5], [7,1,3]])

##sum
summ1 =a.sum()
summ2 = np.sum(a)

print(summ1)
print(summ2)

19
19


In [24]:
## sum of array column
sum1row = a.sum(axis=1) ##changed axis from 0 to 1
sum2row = np.sum(a,axis=0)
print(sum1row)


[ 8 11]


In [26]:
##maximum overall
maxi = a.max(axis=1) ##chaged/added axis and printed max on each row
print(maxi)

[5 7]


In [27]:
##mean
average = np.mean(a, axis = 0)
print(average)

[4.  1.5 4. ]


In [29]:
##standard deviation
stand_dev = np.std(a,axis=0)
print(stand_dev)

[3.  0.5 1. ]


In [35]:
## task 1
from numpy import linalg as la
A = np.array([0,0])
B = np.array([0,3])
C = np.array([1.5, 0])



In [36]:
AB = la.norm(A-B)
AC = la.norm(A-C)
BC = la.norm(B-C)

In [38]:
print(AB)

3.0


In [39]:
print(AC)

1.5


In [40]:
print(BC)

3.3541019662496847


In [41]:
e= np.array([[1,2,5], [7,1,3]])

print(e)

#transpose = (exchanging/flipping axis)


[[1 2 5]
 [7 1 3]]


In [42]:
###flipping axys where rows become columns and viceversa
tr1 = np.transpose(e)
tr2 = e.T

print(tr1)
print(tr2)

[[1 7]
 [2 1]
 [5 3]]
[[1 7]
 [2 1]
 [5 3]]


In [47]:
## reshape array

reshape = np.reshape(e,(3,2))

#or

reshape2 = e.reshape(3,2)

print(reshape)

print(reshape2)

[[1 2]
 [5 7]
 [1 3]]
[[1 2]
 [5 7]
 [1 3]]


In [ ]:
#NumPy Array Manipulation

In [48]:
## horizontal stacking
f=np.array([[7,8], [4,1]])
g=np.array([[9], [9]])

##hstack
efg=np.hstack([e, f, g])

print(efg)


[[1 2 5 7 8 9]
 [7 1 3 4 1 9]]


In [49]:
##verticcal stacking

i = np.array([3,4,1])
j = np.array([[4,4,4],[7,7,7]])

##vertical stacking
eij = np.vstack([e,i,j])
print(eij)

[[1 2 5]
 [7 1 3]
 [3 4 1]
 [4 4 4]
 [7 7 7]]


In [ ]:
## NUmPy Array I/OS

In [51]:
x = np.array([[1,2,5], [7,1,3]])
y = np.array([[7,8], [4,1]])

##save an array to a binary file(.npy)
np.save("array_a",x)

In [52]:
##save several arrasy to file (default file extension is .npz)
np.savez("array_xy", arr1 =x, arr2 = y)

In [53]:
## save an array in a text file (.txt)

np.savetxt("array_x.txt",x)

In [55]:
## save to a text file but indicate a separator and the data type we want
# 5d means integer
# %s means string
# %f means float
np.savetxt("array_x2.txt", x, delimiter=",", fmt="%.2f")

In [56]:
# save to a csv file
np.savetxt("array_x6.csv", y, delimiter = ",", fmt = "%d")

In [57]:
## loading the .npy file
ANPY= np.load("array_a.npy") 

### load the content array in the .npz file
content = np.load("array_xy.npz")
file1 = content["arr1"]
file2 = ["arr2"]

##open the .txt file
atx1 = np.loadtxt("array_x.txt")
atx2 = np.loadtxt("array_x4.txt", delimiter= ",")

#read the csv file
acsv = np.loadtxt("array_x6.csv", delimiter=",")


FileNotFoundError: array_x4.txt not found.

In [58]:
print(ANPY)

[[1 2 5]
 [7 1 3]]


In [59]:
print(file1)

[[1 2 5]
 [7 1 3]]


In [60]:
print(file2)

['arr2']


In [61]:
print(atx1)

[[1. 2. 5.]
 [7. 1. 3.]]


In [62]:
print(atx2)

NameError: name 'atx2' is not defined

In [63]:
print(acsv)

NameError: name 'acsv' is not defined

In [70]:
##
data=np.array([[1.99, 2.23], [7.75, 1.89], [3.50,4.77]])

#rounding the array to 1 decimal place and converting to a string

round_data = np.round(data, 1).astype(str)
 
## create a row header and join it with the array
row_header = np.array([["r1"],["r2"],["r3"]])
##joining header with the data
data_with_row_header = np.hstack(row_header,round_data)


##adding column header to the data

column_header= ["c1,"c2", "c3"]

header = ",".join(column_header)


##save the data in csv file

np.savetxt("result.csv", data_with_row_header, delimiter=",",fmt="%s", header=header,)


SyntaxError: unterminated string literal (detected at line 16) (526929818.py, line 16)

In [67]:
print(data_with_row_header)

NameError: name 'data_with_row_header' is not defined